name: Test Builds

on:
  push:
    branches-ignore:
      - main
      - master

# Ensures that only one deploy task per branch/environment will run at a time.
concurrency:
  group: environment-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        packagePath:
          - packages/web
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: INSTALL
        run: |
          make -C ${{ matrix.packagePath }} install

      - name: TEST
        run: |
          make -C ${{ matrix.packagePath }} test

      - name: LINT
        run: |
          make -C ${{ matrix.packagePath }} lint

      - name: BUILD
        run: |
          make -C ${{ matrix.packagePath }} build
